// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "660217392cbd84eaa5c92d6371da04a9"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"28b3af7629381a338d41c4d605c1659b": "1f8b08000000000000ff5256d44fcaccd32fcee0e24acf2c5148492d4e2eca4c4a05040000ffff601451af17000000",
		"331fe9d3ed3849a14ce85fecfd59508e": "1f8b08000000000000ff5490c1cedb201084ef3cc5165ffa1f0c494e15a73c44ef15c6d8ac62b3880554abedbb57b11d2939b1c37cb38ce8a0046440060b6cd7b478e0baae14c1519c708609172f3a60ef219492d8683d630975508e563dda86233574411fb1ee88d56c0b5214cd67468a06aec22e68d9b3813f72c6d29f8e3420078cfa948a83fc273aa05a522d236603929acf19c7d1c75f236629fc6fef8c00182c87e70910fcb250bfeb63561c04c04c0346e8738d0796ac7b64036ff5671aea34d985f4eee9763b86dbceeff90f7eddb0b8a677e3de2eeaa27e9c64b0eef181669a934fc9ebc3bbb7abbaa8e7deb49540117af7d6ddc0df5d00e09a2817e08dcf8b943196efbcb13abfe8eb454ef033576f4ef922e5be10a64cebf9d437f925c4ff000000ffff33e910ace8010000",
		"a24a41abb2f5d6e7d1ad3c1f697a1e63": "1f8b08000000000000ff24ca410ac2301085e17d4ef1c8013c805b11ba11179e20a54333904e42f26a859abb4bebf6ff3f466dd086491bab8e2bc39804940fdda68cd8775c6ed92846f4eedcab549d41594a0a549b0fe0a3a4943dbe584b917aba2950aec7b4bc9d61c8cb3f88bde187e7e3eed1fb2f0000ffffb84780aa7f000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("Summon Box", "../assets")
		b.SetResolver("bin/version.sh", packr.Pointer{ForwardBox: gk, ForwardPath: "28b3af7629381a338d41c4d605c1659b"})
		b.SetResolver("summon.config.yaml", packr.Pointer{ForwardBox: gk, ForwardPath: "331fe9d3ed3849a14ce85fecfd59508e"})
		b.SetResolver("text.txt", packr.Pointer{ForwardBox: gk, ForwardPath: "a24a41abb2f5d6e7d1ad3c1f697a1e63"})
	}()

	return nil
}()
