// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "660217392cbd84eaa5c92d6371da04a9"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"28b3af7629381a338d41c4d605c1659b": "1f8b08000000000000ff5256d44fcaccd32fcee0e24acf2c5148492d4e2eca4c4a05040000ffff601451af17000000",
		"331fe9d3ed3849a14ce85fecfd59508e": "1f8b08000000000000ff6c534d6fe33610bdeb57bca50daf7d9068fb602c5418d89eda535b14b91545405394c49ae210fc506a24f9ef8524c67580bd881cbe378fc337a31562af037480401083330a210d035948b2adeed06aa38a158252e86374a1e6bcd3b14f974ad2c01b31ea86462d7bbea4ad96b4e445d4648b51f9a0c9d63814c2681154a8f1ca3a1dcb8cb01aeca22dcf61157af65eac4029ba141bed6b301a95f7ba69947d6eb46785fa57c9ba002e22f4d30af4ca182ae778d957a12f808e2edaa2f4c92e3427e4d5d77828bfa34b6a5b6188cf181f8fcbe638f3e7fc4ffce1a6a31cf90c7c1ff7d5befa9699bd90d74f544f9d53ce29be60dfc743b5af265d778b3d5994f2a1f61a6f7300e8c1918f08b7900f9cd7366ec32d54d9a2dd07b3c5934faacee10793cd82683d0df9aa2f6c5764bbeeb7ae1006610cda64e5d4284442503139084435d520fc0dbffcfec7cf4fbf42d2e044d417a3d051431241f95179681b74a3d090bc2aff21fbe339e9c808dbf18eb80e21a9c08fa76fc70a4fd3ec0963e825cca2da76935c1a948dcb002daa2d79087484819a645480b2e2625403e7e91f256395bbd090fcdfcafbdb9e6760bbc3ebddabbff005650bb6deba9766c73baa066a18fec66603257b0253ded3342c33024b112d25db30bcbddd5590eb39afb7e2e58aafbffd793e1f5ee73e607d7cff9ab377d86c1e7216bfe0934559fa01a5025b9c3ef33838de1143e970da9ff6f5f4413962a9b3ce380f5ef2f57237166beb4375385627f0e967caad069b9f32b5a3e6dc9014a6a7106751eeaedd5d62b3c98d2d27ee7926b0878a930d2a4e7e2d4efe94a1f7bc2ea745f15f000000fffffdc3e34a4c040000",
		"a24a41abb2f5d6e7d1ad3c1f697a1e63": "1f8b08000000000000ff24ca410ac2301085e17d4ef1c8013c805b11ba11179e20a54333904e42f26a859abb4bebf6ff3f466dd086491bab8e2bc39804940fdda68cd8775c6ed92846f4eedcab549d41594a0a549b0fe0a3a4943dbe584b917aba2950aec7b4bc9d61c8cb3f88bde187e7e3eed1fb2f0000ffffb84780aa7f000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("Summon Box", "../assets")
		b.SetResolver("bin/version.sh", packr.Pointer{ForwardBox: gk, ForwardPath: "28b3af7629381a338d41c4d605c1659b"})
		b.SetResolver("summon.config.yaml", packr.Pointer{ForwardBox: gk, ForwardPath: "331fe9d3ed3849a14ce85fecfd59508e"})
		b.SetResolver("text.txt", packr.Pointer{ForwardBox: gk, ForwardPath: "a24a41abb2f5d6e7d1ad3c1f697a1e63"})
	}()

	return nil
}()
