// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "660217392cbd84eaa5c92d6371da04a9"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"28b3af7629381a338d41c4d605c1659b": "1f8b08000000000000ff5256d44fcaccd32fcee0e24acf2c5148492d4e2eca4c4a05040000ffff601451af17000000",
		"331fe9d3ed3849a14ce85fecfd59508e": "1f8b08000000000000ff5490b18ee32010867b9e628e3497c2384975a2ca435c7fc23636a3180631609db5bbefbe0a26d2a6627ebe8f1fc409b243066430c0c6c7d50217ef29c04861c605665cadd86c62a4a0e12acc8a862d6bf8900be6ae11a9410e18fa16153bf9254e4025c792274c1a246d36259c261bfe4d98a4b0ffeda805c060d83d570067d795ba9a8f59b113000b0d18a04b251c5a34e323695830bb32a8917cbfd050e6d9acd457d66fb763b855bf9e7ff3fd8e79dcfa0aeedb455dd49f663a333eded4444bb431dafe60f7edaa2eead91bf7ec284037fe78bb86cf1a00d0474a1978e7b6111386fc9b7756ed8bce2f7386bfa958dde2cb94b510e644be5df54b9e85f80e0000ffffb578adbfaf010000",
		"a24a41abb2f5d6e7d1ad3c1f697a1e63": "1f8b08000000000000ff24ca410ac2301085e17d4ef1c8013c805b11ba11179e20a54333904e42f26a859abb4bebf6ff3f466dd086491bab8e2bc39804940fdda68cd8775c6ed92846f4eedcab549d41594a0a549b0fe0a3a4943dbe584b917aba2950aec7b4bc9d61c8cb3f88bde187e7e3eed1fb2f0000ffffb84780aa7f000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("Summon Box", "../assets")
		b.SetResolver("bin/version.sh", packr.Pointer{ForwardBox: gk, ForwardPath: "28b3af7629381a338d41c4d605c1659b"})
		b.SetResolver("summon.config.yaml", packr.Pointer{ForwardBox: gk, ForwardPath: "331fe9d3ed3849a14ce85fecfd59508e"})
		b.SetResolver("text.txt", packr.Pointer{ForwardBox: gk, ForwardPath: "a24a41abb2f5d6e7d1ad3c1f697a1e63"})
	}()

	return nil
}()
