# this is a sample summon config file
# see https://github.com/davidovich/summon#configuration
version: 1
aliases: {"git-version": "bin/version.sh"}
# outputdir: "overridden_dir"
exec:
  bash:
    hello-bash: hello.sh
  gobin -run:
    packr: github.com/gobuffalo/packr/v2/packr2
    gobin: github.com/myitcv/gobin@v0.0.8
    gohack: github.com/rogpeppe/gohack@v1.0.2
  python -c:
    hello: |
      import sys
      print(sys.version)
      if True:
        print("hello from python!")

  bash -c:
    # small function to setup a temporary GOPATH compatible godoc server inside docker
    # see https://github.com/golang/go/issues/2682. This allows serving documentation
    # for a go modules enabled project.
    godoc: |
      function _godoc() {
        [ ! -f "$(pwd)/go.mod" ] && echo "error: go.mod not found" ||
          module=$(awk 'NR==1{print $2}' go.mod) &&
          docker run --rm -e "GOPATH=/tmp/go" -p 6060:6060 -v $(pwd):/tmp/go/src/$module golang:1.12.6 /bin/bash -c "echo http://localhost:6060/pkg/$module && godoc -http=:6060"
          unset -f _godoc;
      }
      _godoc

