# this is a sample summon config file
# see https://github.com/davidovich/summon#configuration
version: 1
aliases: {"git-version": "bin/version.sh"}
# outputdir: "overridden_dir"
exec:
  bash:
    hello-bash: hello.sh
  gobin -run:
    packr: github.com/gobuffalo/packr/v2/packr2
    gobin: github.com/myitcv/gobin@v0.0.8
    gohack: github.com/rogpeppe/gohack@v1.0.2
  python -c:
    hello: |
      import sys
      print(sys.version)
      if True:
        print("hello from python!")

