// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "77e95650ae6448f85ba6148e572023c0"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"28b3af7629381a338d41c4d605c1659b": "1f8b08000000000000ff5256d44fcaccd32fcee0e24acf2c5148492d4e2eca4c4a05040000ffff601451af17000000",
		"331fe9d3ed3849a14ce85fecfd59508e": "1f8b08000000000000ff5490bd6ee33010847b3ec59cdc9c0b4b3e5707567988f4014551e2c22297e052428424ef1e849201a7e20ce7db1fec09c59380040662429a1d640981232cc791268c343bb5ba2cc451e39f32331971a2f1f1a54ee0a5a4a50c94351a5e5dce340c2ebe0d941be5de9dd50ae88df89f17f06e9ef952fdae5bf10a98b8a7b813c9d87bd698a8f8a56f2d876ee27e1947337357b36ebdede256f9bdf4990f1b15bb76357859afedb5fd7f90ded8fb2f34f3945c4aaedb3305a4ad788eb8d8a77d353eab012824ce05b2c9f19132c5f25736698f039d1fe488d7bc387dd807d9d48618338763d49fe6acd477000000ffff8f63e4cb84010000",
		"a24a41abb2f5d6e7d1ad3c1f697a1e63": "1f8b08000000000000ff2ac9c82c56c82c5648542849ad2801040000ffff213eeaee0e000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("Summon Box", "../assets")
		b.SetResolver("bin/version.sh", packr.Pointer{ForwardBox: gk, ForwardPath: "28b3af7629381a338d41c4d605c1659b"})
		b.SetResolver("summon.config.yaml", packr.Pointer{ForwardBox: gk, ForwardPath: "331fe9d3ed3849a14ce85fecfd59508e"})
		b.SetResolver("text.txt", packr.Pointer{ForwardBox: gk, ForwardPath: "a24a41abb2f5d6e7d1ad3c1f697a1e63"})
	}()

	return nil
}()
