// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "77e95650ae6448f85ba6148e572023c0"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"85c3031c50b89b6f8895e52bb5bec52f": "1f8b08000000000000ff4acf2cc9284dd24bcecfd54fcf4f2a4d4b4bccc9d72f484cce2ed22f3382308c00010000ffff1234fda224000000",
		"a24a41abb2f5d6e7d1ad3c1f697a1e63": "1f8b08000000000000ff2ac9c82c56c82c5648542849ad2801040000ffff213eeaee0e000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("Summon Box", "../assets")
		b.SetResolver("bin/packr2.gobin.summon", packr.Pointer{ForwardBox: gk, ForwardPath: "85c3031c50b89b6f8895e52bb5bec52f"})
		b.SetResolver("text.txt", packr.Pointer{ForwardBox: gk, ForwardPath: "a24a41abb2f5d6e7d1ad3c1f697a1e63"})
	}()

	return nil
}()
